---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      # - id: double-quote-string-fixer
      - id: pretty-format-json
        args: ["--autofix"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  # Automatically run pytests locally
  - repo: local
    hooks:
      - id: tests
        name: Run pytest
        entry: pytest -v
        pass_filenames: false
        language: system
        types: [python]
        stages: [commit]
        always_run: true
  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.10.0
    hooks:
      - id: hadolint-docker
  # Makefile linting
  #- repo: https://github.com/Lucas-C/pre-commit-hooks-go
  #  rev: v1.0.1
  #  hooks:
  #    - id: checkmake
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: "\\.(py)$"
        name: isort (python)
        args: [--settings-path=pyproject.toml]
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
#  - repo: https://github.com/jumanjihouse/pre-commit-hooks
#    rev: 3.0.0
#    hooks:
#      - id: markdownlint
#      - id: shfmt
